#!/bin/bash

echo "=== Nginx Container Deployment Options ==="

# Option 1: Direct LXC Commands (requires sudo)
echo -e "\033[1;33m=== Option 1: Direct LXC Commands ===\033[0m"
echo "1. Create container:"
echo "   sudo /usr/bin/lxc-create -t ubuntu -n nginx-web"
echo ""
echo "2. Configure container:"
echo "   sudo /usr/bin/lxc-execute nginx-web -- apt-get update"
echo "   sudo /usr/bin/lxc-execute nginx-web -- apt-get install -y nginx curl"
echo ""
echo "3. Setup web content:"
echo "   sudo /usr/bin/lxc-execute nginx-web -- bash -c 'echo \"<h1>Hello from Nginx LXC!</h1>\" > /var/www/html/index.html'"
echo ""
echo "4. Start container:"
echo "   sudo /usr/bin/lxc-start nginx-web"
echo ""
echo "5. Get container info:"
echo "   sudo /usr/bin/lxc-info nginx-web"
echo ""
echo "6. Test web server:"
echo "   sudo /usr/bin/lxc-execute nginx-web -- curl -I http://localhost"
echo ""

# Option 2: API-based (requires API running)
echo -e "\033[1;33m=== Option 2: API-based Testing ===\033[0m"
echo "1. Create container via API:"
echo "   curl -X POST http://localhost:8080/api/v1/containers \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"name\":\"nginx-api\",\"template\":\"ubuntu\",\"config\":{\"cpu_limit\":1}}'"
echo ""
echo "2. Start container:"
echo "   curl -X POST http://localhost:8080/api/v1/containers/nginx-api/start"
echo ""
echo "3. Install nginx:"
echo "   curl -X POST http://localhost:8080/api/v1/containers/nginx-api/exec \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"command\":\"apt-get update && apt-get install -y nginx\"}'"
echo ""
echo "4. Create web content:"
echo "   curl -X POST http://localhost:8080/api/v1/containers/nginx-api/exec \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"command\":\"echo \\\"<h1>Hello from API-managed Nginx!</h1>\\\" > /var/www/html/index.html\"}'"
echo ""
echo "5. Start nginx:"
echo "   curl -X POST http://localhost:8080/api/v1/containers/nginx-api/exec \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"command\":\"systemctl start nginx\"}'"
echo ""

# Option 3: Simulation/Mock Testing
echo -e "\033[1;33m=== Option 3: Simulation Testing ===\033[0m"
echo "1. Mock container creation response:"
echo "   curl -s -X POST http://localhost:8080/api/v1/containers \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"name\":\"nginx-sim\",\"template\":\"ubuntu\",\"config\":{\"cpu_limit\":1}}' \\"
echo "     -H 'X-API-Mock: true'"
echo ""
echo "2. Mock nginx installation:"
echo "   echo 'Simulating nginx installation...'"
echo ""
echo "3. Mock service start:"
echo "   echo 'Simulating nginx service start...'"
echo ""

echo "=== Testing Commands ==="
echo "Check API health: curl -s http://localhost:8080/health | jq ."
echo "List containers: curl -s http://localhost:8080/api/v1/containers | jq ."
echo "Container details: curl -s http://localhost:8080/api/v1/containers/nginx-test | jq ."
echo ""
echo "=== Choose your testing method above ==="
